language: node_js
node_js:
  - '0.10'
before_install:
  - npm install -g gulp
  - sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
install:
  - npm install
after_install:
  - gulp check-updates
after_success:
  - gulp coveralls
